"""empty message

Revision ID: 0f145316c02b
Revises: 56a60e4e7bbd
Create Date: 2025-11-22 14:05:28.036792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f145316c02b'
down_revision = '56a60e4e7bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS customer_profile CASCADE")
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('user_phone', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('user_reg_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('userpassword', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        #batch_op.drop_constraint(batch_op.f('customer_customer_username_fkey'), type_='foreignkey')
        batch_op.drop_column('customer_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_username', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('customer_customer_username_fkey'), 'customer_profile', ['customer_username'], ['username'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userpassword')
        batch_op.drop_column('user_reg_date')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_phone')
        batch_op.drop_column('username')

    op.create_table('customer_profile',
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('user_phone', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('user_reg_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('userpassword', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('username', name=op.f('customer_profile_pkey'))
    )
    # ### end Alembic commands ###
