"""users table

Revision ID: 103648184c54
Revises: 
Create Date: 2025-11-20 15:25:19.137708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103648184c54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profile',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('user_phone', sa.String(length=11), nullable=True),
    sa.Column('user_email', sa.String(length=30), nullable=True),
    sa.Column('user_reg_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('it_profile',
    sa.Column('d_username', sa.String(length=30), nullable=False),
    sa.Column('d_phone', sa.String(length=11), nullable=False),
    sa.Column('d_email', sa.String(length=30), nullable=False),
    sa.Column('d_reg_date', sa.Date(), nullable=False),
    sa.Column('d_last_paid', sa.Date(), nullable=True),
    sa.Column('d_license_stat', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('d_username')
    )
    op.create_table('registered_users',
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('userpassword', sa.String(length=255), nullable=False),
    sa.Column('userrole', sa.String(length=15), nullable=False),
    sa.CheckConstraint("userrole IN ('ADMIN','CUSTOMER','VENDOR','DELIVERY')", name='role_check'),
    sa.PrimaryKeyConstraint('register_id')
    )
    op.create_table('vendor_profile',
    sa.Column('v_username', sa.String(length=30), nullable=False),
    sa.Column('v_phone', sa.String(length=11), nullable=False),
    sa.Column('v_email', sa.String(length=30), nullable=False),
    sa.Column('v_reg_date', sa.Date(), nullable=False),
    sa.Column('v_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('v_username')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_username', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['vendor_username'], ['vendor_profile.v_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('vendor')
    op.drop_table('vendor_profile')
    op.drop_table('registered_users')
    op.drop_table('it_profile')
    op.drop_table('customer_profile')
    # ### end Alembic commands ###
