"""empty message

Revision ID: 10b6f84b532c
Revises: 396a86f1f21b
Create Date: 2025-11-23 18:18:56.485030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b6f84b532c'
down_revision = '396a86f1f21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('total')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('rating_count')

    # ### end Alembic commands ###
