"""empty message

Revision ID: 15b8f11aaffb
Revises: 6075662f2774
Create Date: 2025-11-21 14:11:45.650824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b8f11aaffb'
down_revision = '6075662f2774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('delivery_person_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('instructions', sa.String(length=256), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','ACCEPTED','REJECTED','PREPPING','DISPATCHED','DONE')", name='order_status_check'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['delivery_person.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['menu.item_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
