"""empty message

Revision ID: 396a86f1f21b
Revises: 3167d9882b85
Create Date: 2025-11-22 23:57:30.241082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396a86f1f21b'
down_revision = '3167d9882b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('Type', sa.String(length=35), nullable=True))
        batch_op.drop_column('item_name')
        batch_op.drop_column('item_Type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_Type', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('Type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
