"""empty message

Revision ID: 4d843ec4ab06
Revises: 15b8f11aaffb
Create Date: 2025-11-21 17:21:17.936278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d843ec4ab06'
down_revision = '15b8f11aaffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_profile', schema=None) as batch_op:
        batch_op.alter_column('user_phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_paid', sa.Date(), nullable=True))

    with op.batch_alter_table('it_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('v_verified', sa.Boolean(), nullable=False))
        batch_op.drop_column('d_last_paid')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('order_timestamp')

    with op.batch_alter_table('it_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d_last_paid', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('v_verified')

    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.drop_column('last_paid')

    with op.batch_alter_table('customer_profile', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('user_phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)

    # ### end Alembic commands ###
