"""empty message

Revision ID: 56a60e4e7bbd
Revises: 4d843ec4ab06
Create Date: 2025-11-22 12:17:47.230124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a60e4e7bbd'
down_revision = '4d843ec4ab06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userpassword', sa.String(length=255), nullable=False))

    with op.batch_alter_table('it_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userpassword', sa.String(length=255), nullable=False))

    with op.batch_alter_table('vendor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userpassword', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profile', schema=None) as batch_op:
        batch_op.drop_column('userpassword')

    with op.batch_alter_table('it_profile', schema=None) as batch_op:
        batch_op.drop_column('userpassword')

    with op.batch_alter_table('customer_profile', schema=None) as batch_op:
        batch_op.drop_column('userpassword')

    # ### end Alembic commands ###
