"""empty message

Revision ID: 6075662f2774
Revises: 103648184c54
Create Date: 2025-11-21 12:36:26.720844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6075662f2774'
down_revision = '103648184c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=15, scale=10), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=15, scale=10), nullable=False),
    sa.Column('full_address', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('osm_id', sa.String(length=75), nullable=False),
    sa.Column('osm_type', sa.String(length=50), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('customer_username', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['customer_username'], ['customer_profile.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('delivery_username', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('worked_hours', sa.Integer(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('wallet', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.CheckConstraint("status IN ('ON_DUTY','OFF_DUTY','IN_JOB')", name='status_check'),
    sa.ForeignKeyConstraint(['current_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['delivery_username'], ['it_profile.d_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('it_profile', schema=None) as batch_op:
        batch_op.drop_column('d_license_stat')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.String(length=35), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=35), nullable=True))
        batch_op.add_column(sa.Column('Type', sa.String(length=35), nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('working_hours_start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('working_hours_end', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'location', ['vendor_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('working_hours_end')
        batch_op.drop_column('working_hours_start')
        batch_op.drop_column('name')
        batch_op.drop_column('vendor_location_id')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('Type')
        batch_op.drop_column('category')
        batch_op.drop_column('cuisine')

    with op.batch_alter_table('it_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d_license_stat', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.drop_table('delivery_person')
    op.drop_table('customer')
    op.drop_table('location')
    # ### end Alembic commands ###
