"""empty message

Revision ID: 749d3b685f2a
Revises: 0f145316c02b
Create Date: 2025-11-22 17:26:42.453566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '749d3b685f2a'
down_revision = '0f145316c02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS vendor_profile CASCADE")
    op.execute("DROP TABLE IF EXISTS it_profile CASCADE")
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d_username', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('d_phone', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('d_email', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('d_reg_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('v_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('userpassword', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['d_username'])
        #batch_op.drop_constraint(batch_op.f('delivery_person_delivery_username_fkey'), type_='foreignkey')
        batch_op.drop_column('delivery_username')

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('v_username', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('v_phone', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('v_email', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('v_reg_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('v_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('userpassword', sa.String(length=255), nullable=False))
        batch_op.alter_column('working_hours_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('working_hours_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['v_username'])
        #batch_op.drop_constraint(batch_op.f('vendor_vendor_username_fkey'), type_='foreignkey')
        batch_op.drop_column('vendor_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_username', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('vendor_vendor_username_fkey'), 'vendor_profile', ['vendor_username'], ['v_username'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('working_hours_end',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('working_hours_start',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('userpassword')
        batch_op.drop_column('v_verified')
        batch_op.drop_column('v_reg_date')
        batch_op.drop_column('v_email')
        batch_op.drop_column('v_phone')
        batch_op.drop_column('v_username')

    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_username', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('delivery_person_delivery_username_fkey'), 'it_profile', ['delivery_username'], ['d_username'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userpassword')
        batch_op.drop_column('v_verified')
        batch_op.drop_column('d_reg_date')
        batch_op.drop_column('d_email')
        batch_op.drop_column('d_phone')
        batch_op.drop_column('d_username')

    op.create_table('it_profile',
    sa.Column('d_username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('d_phone', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('d_email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('d_reg_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('v_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('userpassword', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('d_username', name=op.f('it_profile_pkey'))
    )
    op.create_table('vendor_profile',
    sa.Column('v_username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('v_phone', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('v_email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('v_reg_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('v_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('userpassword', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v_username', name=op.f('vendor_profile_pkey'))
    )
    # ### end Alembic commands ###
