"""empty message

Revision ID: 75f008971b7a
Revises: a85f675bf30e
Create Date: 2025-12-12 01:16:42.967852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f008971b7a'
down_revision = 'a85f675bf30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_catalog',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=True),
    sa.Column('tag_category', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('item_features',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('feature_version', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_tags',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu.item_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_catalog.tag_id'], ),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tags')
    op.drop_table('item_features')
    op.drop_table('tag_catalog')
    # ### end Alembic commands ###
