"""empty message

Revision ID: 8502c9b17bd4
Revises: 75f008971b7a
Create Date: 2025-12-12 01:43:51.009735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8502c9b17bd4'
down_revision = '75f008971b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d_type', sa.String(length=35), nullable=True))
        batch_op.drop_column('Type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Type', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
        batch_op.drop_column('d_type')

    # ### end Alembic commands ###
