"""empty message

Revision ID: a85f675bf30e
Revises: f44eb3c58982
Create Date: 2025-11-25 00:54:43.745757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85f675bf30e'
down_revision = 'f44eb3c58982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings_count', sa.Integer(), nullable=True))
        batch_op.drop_column('rating_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('ratings_count')

    # ### end Alembic commands ###
