"""empty message

Revision ID: b18124d5cb89
Revises: e6f7df15c021
Create Date: 2025-11-22 23:53:43.591707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18124d5cb89'
down_revision = 'e6f7df15c021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_Type', sa.String(length=35), nullable=True))
        batch_op.drop_column('Type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Type', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
        batch_op.drop_column('item_Type')

    # ### end Alembic commands ###
