"""empty message

Revision ID: cf27e4e4e4c0
Revises: cadcadf8ccc3
Create Date: 2025-11-22 23:08:01.984945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf27e4e4e4c0'
down_revision = 'cadcadf8ccc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vendor', ['vendor_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_item_vendor_id_fkey'), type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('order_item_vendor_id_fkey'), 'vendor', ['vendor_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
