"""empty message

Revision ID: d2a0f1ae5915
Revises: 3ffaf98acf9c
Create Date: 2025-11-22 22:14:52.276852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2a0f1ae5915'
down_revision = '3ffaf98acf9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registered_users')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delivery_person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'PREPPING'::character varying, 'DISPATCHED'::character varying, 'DONE'::character varying]::text[])", name=op.f('order_status_check')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('order_customer_id_fkey')),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['delivery_person.id'], name=op.f('order_delivery_person_id_fkey')),
    sa.ForeignKeyConstraint(['item_id'], ['menu.item_id'], name=op.f('order_item_id_fkey')),
    sa.PrimaryKeyConstraint('order_id', 'item_id', name=op.f('order_pkey'))
    )
    op.create_table('registered_users',
    sa.Column('register_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('userpassword', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('userrole', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.CheckConstraint("userrole::text = ANY (ARRAY['ADMIN'::character varying, 'CUSTOMER'::character varying, 'VENDOR'::character varying, 'DELIVERY'::character varying]::text[])", name=op.f('role_check')),
    sa.PrimaryKeyConstraint('register_id', name=op.f('registered_users_pkey'))
    )
    # ### end Alembic commands ###
