"""empty message

Revision ID: f3a6902e2202
Revises: 10b6f84b532c
Create Date: 2025-11-24 23:24:37.979669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a6902e2202'
down_revision = '10b6f84b532c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offered_to_driver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'delivery_person', ['offered_to_driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('offered_to_driver_id')

    # ### end Alembic commands ###
